using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using NewsAgent.Models;

namespace NewsAgent.Delivery;

/// <summary>
/// Delivers the digest by saving it to a local HTML file.
/// </summary>
public class FileDelivery(
    ILogger<FileDelivery> logger,
    IOptions<DigestConfig> config) : IDigestDelivery
{
    /// <inheritdoc />
    public async Task DeliverAsync(DigestOutput digest, CancellationToken cancellationToken = default)
    {
        var directory = config.Value.Output.FilePath;

        if (!Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        var tz = TimeZoneInfo.FindSystemTimeZoneById(config.Value.Schedule.Timezone);
        var localTime = TimeZoneInfo.ConvertTime(digest.GeneratedAt, tz);
        var fileName = $"digest-{localTime:yyyy-MM-dd-HHmm}.html";
        var outputPath = Path.Combine(directory, fileName);
        var fullHtml = WrapInHtmlDocument(digest.HtmlContent, digest.GeneratedAt);

        await File.WriteAllTextAsync(outputPath, fullHtml, cancellationToken);

        logger.LogInformation("Digest saved to {Path} ({ArticleCount} articles, {Length} chars)",
            outputPath, digest.ArticleCount, fullHtml.Length);
    }

    private static string WrapInHtmlDocument(string content, DateTimeOffset generatedAt)
    {
        var date = generatedAt.ToString("yyyy. MM. dd.");
        return $$"""
            <!DOCTYPE html>
            <html lang="hu">
            <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>AI Hírek Digest</title>
            <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
                background: #f4f4f7;
                color: #1d1d1f;
                line-height: 1.7;
                padding: 24px 16px;
            }
            main {
                max-width: 680px;
                margin: 0 auto;
                background: #ffffff;
                border-radius: 8px;
                padding: 32px 28px;
                box-shadow: 0 1px 4px rgba(0,0,0,0.08);
            }
            h1 {
                font-size: 1.6em;
                color: #1a1a2e;
                margin-bottom: 8px;
            }
            h2 {
                font-size: 1.2em;
                color: #1a1a2e;
                margin-top: 24px;
                margin-bottom: 12px;
            }
            p { margin-bottom: 12px; }
            a { color: #1a6dd4; text-decoration: none; }
            a:hover { text-decoration: underline; }
            hr {
                border: none;
                border-top: 1px solid #e0e0e6;
                margin: 20px 0;
            }
            footer {
                max-width: 680px;
                margin: 16px auto 0;
                text-align: center;
                font-size: 0.8em;
                color: #888;
            }
            @media (max-width: 600px) {
                body { padding: 12px 8px; }
                main { padding: 20px 16px; }
            }
            </style>
            </head>
            <body>
            <main>
            {{content}}
            </main>
            <footer>Generated by News Agent | {{date}}</footer>
            </body>
            </html>
            """;
    }

}
